In [3]:
print("Hii")

Hii


In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

arr1 = np.array([1,2,3,4,5,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 5]
<class 'numpy.ndarray'>
(6,)


In [6]:
## Reshaping the array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [7]:
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [8]:
# 0 to 10 with jump of 2
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# Attributes of numpy

arr = np.array([[1,2,3], [4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape) ## output (2,3)
print("Number of Dimensions:", arr.ndim) ## output: 2
print("Size (Number of elements):", arr.size) ## output: 6
print("Data type:", arr.dtype) ## output: int64 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize) ## output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimensions: 2
Size (Number of elements): 6
Data type: int64
Item size (in bytes): 8


In [12]:
# Numpy vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise addition
print("Addition: ", arr1+arr2)

# Element wise Substraction
print("Substraction: ", arr1-arr2)

# Element wise Multiplication
print("Multiplication: ", arr1*arr2)

# Element wise division
print("Division: ", arr1/arr2)


Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [13]:
#  Universal Function
arr=np.array([1,2,3,4,5,6])

# Square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [15]:
import numpy as np

In [16]:
# Array slicing and indexing

arr=np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
arr[0][1] ## 0th row, 1st column

np.int64(2)

In [18]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [20]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [21]:
# Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [22]:
# Stastistical concepts -- Normalization
# to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
nor_data = (data - mean)/std_dev
print("Normalized data: ", nor_data)




Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [23]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print(mean)

# Median
median = np.median(data)
print(median)

# Standard deviation
std_dev = np.std(data)
print(std_dev)

# Variance
v = np.var(data)
print(v)

5.5
5.5
2.8722813232690143
8.25


In [27]:
# Logical Operators

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data[(data>5) & (data<9)]

array([6, 7, 8])